name: Build and Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install web dependencies
        run: cd web && npm install
      - name: Create Python Virtual Environment
        run: python -m venv .venv
      - name: Install Python package
        run: pip install -e python/
      - name: Build JSON data
        run: swdata build-elections
      - name: Build Web Application
        run: swdata build-web

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: cd web && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: cd web && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz
